# Generated by Django 4.2.3 on 2023-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_image_time_alter_image_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="time",),
        migrations.AlterField(
            model_name="image",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
